task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

# num_classes: 365
# remap_mscoco_category: False

# num_classes: 91
# remap_mscoco_category: False

num_classes: 10
remap_mscoco_category: True


train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /root/code/rtdetr/dataset/Visdrone/init/train/images
    ann_file: /root/code/rtdetr/dataset/Visdrone/init/train/train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 1
  drop_last: True 
  collate_fn:
    type: BatchImageCollateFuncion


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /root/code/rtdetr/dataset/Visdrone/VisDrone/val/images
    ann_file: /root/code/rtdetr/dataset/Visdrone/VisDrone/val/val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~ 
  shuffle: False
  num_workers: 1
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion
